[general]
import = [
  "./theme-ayu-dark.toml"
]

[font]
size = 12
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
offset.y = 0
glyph_offset.y = 0

[window]
padding = { x = 2, y = 0 }
decorations = "None"

